-- CreateEnum
CREATE TYPE "Estado" AS ENUM ('POR_HACER', 'EN_PROCESO', 'HECHO', 'ENTREGADO');

-- AlterTable
ALTER TABLE "User" ADD COLUMN     "estado" "Estado" NOT NULL DEFAULT 'POR_HACER',
ADD COLUMN     "pagado" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "senia" DOUBLE PRECISION NOT NULL DEFAULT 0;
